apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition: |
    openapi: "3.0.0"
    info:
      version: <b>aaa</b>
      title: Artist API
      license:
        name: MIT
    servers:
      - url: javascript:alert(1)
    paths:
      /artists:
        get:
          summary: List all artists
    ...